### ISSUE TITLE
hot css with linaria rollup plugin

### ISSUE THREAD

**Issue by high1** [PepsRyuu/rollup-plugin-hot-css#3]
This is more of a question than an issue... I've seen that linaria has a rollup [plugin](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#rollup), and the plugin works - but breaks the hotcss reloading if used with nollup. Could these two work together?

**Comment by PepsRyuu** [comment]
Not familiar with Linaria at all, can you explain in more detail what the error is? Does a CSS file still get extracted correctly? Is it just the HMR aspect that's broke?

**Comment by high1** [comment]
Linaria is a CSS in JS library which does not have a runtime, component stylings are transformed to CSS during compilation. Just the HMR functionality does not work.

**Comment by PepsRyuu** [comment]
Doesn't look like it's possible because of the coding of Linaria. Here's what's happening:

* Nollup starts compilation.
* Nollup loads JS file.
* Linaria plugin triggers, detects CSS block, extracts it, injects ```import``` for an auto-generated CSS file with a hash.
* Nollup sees the import statement, tries to load the CSS file.
* Linaria plugin provides the CSS file.
* CSS file gets picked up by ```hotcss```.

That's all well and good for the initial load, works as expected, but here's the HMR flow:

* Nollup sees that JS file has changed, invalidates and reloads that file.
* Linaria plugin extracts the CSS, updates the content of the CSS file and appends the exact same ```import``` statement.
* Nollup isn't aware that the content of the CSS file has changed, nor has any reason to think so, so it doesn't reload it.

This isn't possible to fix in either ```nollup``` or ```rollup-plugin-hot-css```, it's a bug for ```linaria```. They can fix it by changing their hashing to be based on the ```cssText``` instead of the generated filename. This will create a new dependency in the JS file which Nollup will detect and try to then load.

```
var cssText = result.cssText;
var slug = slugify(id); <-- change this to "slugify(cssText)"
var filename = id.replace(/\.js$/, '') + "_" + slug + ".css";
```

I suggest writing an issue on their end with the fix proposal and see what they think.

**Comment by high1** [comment]
Thanks, I will provide a link to this conversation.
